### ISSUE TITLE
TokenError: Code was already redeemed and TokenError: Bad Request

### ISSUE THREAD

**Issue by carbonizon** [jaredhanson/passport-google-oauth2#15]
I have a pretty basic passport setup as you can see below. Every once in a while I get two different errors. `TokenError: Code was already redeemed` and `TokenError: Bad Request` for reasons I cannot seem to find.

I've looked around a lot (1 week) for possible solutions but am yet to find one which works.

Do you see anything wrong with the current code?

	app.get('/auth/google', redirect, passport.authenticate('google', { scope: ['profile', 'email'] }));

	app.get('/auth/google/callback', passport.authenticate('google', { failureRedirect: '/' }),
	  function(req, res) {
	    res.redirect('/');
	  }
	);
**Here are the two errors:**

    TokenError: Bad Request 
      at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:320:12) 
      at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:367:16) 
      at /app/node_modules/passport-oauth2/lib/strategy.js:166:45 
      at /app/node_modules/oauth/lib/oauth2.js:177:18 
      at passBackControl (/app/node_modules/oauth/lib/oauth2.js:123:9) 
      at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:143:7) 
      at emitNone (events.js:85:20) 
      at IncomingMessage.emit (events.js:179:7) 
      at endReadableNT (_stream_readable.js:913:12) 
      at _combinedTickCallback (internal/process/next_tick.js:74:11) 
      at process._tickCallback (internal/process/next_tick.js:98:9)
      

    TokenError: Code was already redeemed. 
          at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:320:12) 
          at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:367:16) 
          at /app/node_modules/passport-oauth2/lib/strategy.js:166:45 
          at /app/node_modules/oauth/lib/oauth2.js:177:18 
          at passBackControl (/app/node_modules/oauth/lib/oauth2.js:123:9) 
          at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:143:7) 
          at emitNone (events.js:85:20) 
          at IncomingMessage.emit (events.js:179:7) 
          at endReadableNT (_stream_readable.js:913:12) 
          at _combinedTickCallback (internal/process/next_tick.js:74:11) 
          at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ckelner** [comment]
👍

**Comment by njbraun** [comment]
After a bit of digging, it looks like failureRedirect is ONLY used for strategy 'failures' and not 'errors', which is what gets thrown if a Token has already been used/redeemed.

This is a bit confusing, I agree.

It's almost as if passport needs an additional option for 'errorRedirect'

You can handle this outside of passport by implementing your own error handling. For example:

```javascript
app.get('/auth/google/callback',
  passport.authenticate('google'), // complete the authenticate using the google strategy
  (err, req, res, next) => { // custom error handler to catch any errors, such as TokenError
    if (err.name === 'TokenError') {
     res.redirect('/auth/google'); // redirect them back to the login page
    } else {
     // Handle other errors here
    }
  },
  (req, res) => { // On success, redirect back to '/'
    res.redirect('/');
  }
);
```

**Comment by prabhakarupadhyay** [comment]
someone please give a solution to that problem i have tried almost everything on internet but that shit just fails to work in the deployment even though it works fine on other cloud platform and even on localhost

**Comment by thomasbromehead** [comment]
Still struggling with this too ...

**Comment by Suyash-Purwar** [comment]
I am getting only first error: TokenError: Bad Request

I have no idea what to do.

**Comment by dennyferra** [comment]
Try inspecting the TokenError (in my case the **code** property was helpful). If you're using express and errorHandler you can get some additional detail by manually logging the error:

```javascript
  app.use(errorHandler({ log: errorNotification }));

  function errorNotification(err, str, req) {
    console.log('ERROR', err);
  }
```
This allowed me to see the `code` property (redirect_uri_mismatch) which helped me determine the actual issue.

> ERROR! { TokenError: Bad Request
>     at Strategy.OAuth2Strategy.parseErrorResponse (/home/ec2-user/environment/revtm/node_modules/passport-oauth2/lib/strategy.js:345:12)
>     at Strategy.OAuth2Strategy._createOAuthError (/home/ec2-user/environment/revtm/node_modules/passport-oauth2/lib/strategy.js:394:16)
>     at /home/ec2-user/environment/revtm/node_modules/passport-oauth2/lib/strategy.js:172:45
>     at /home/ec2-user/environment/revtm/node_modules/oauth/lib/oauth2.js:191:18
>     at passBackControl (/home/ec2-user/environment/revtm/node_modules/oauth/lib/oauth2.js:132:9)
>     at IncomingMessage.<anonymous> (/home/ec2-user/environment/revtm/node_modules/oauth/lib/oauth2.js:157:7)
>     at IncomingMessage.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1081:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>   name: 'TokenError',
>   message: 'Bad Request',
>   **code: 'redirect_uri_mismatch',**
>   uri: undefined,
>   status: 500 }

**Comment by akash5324** [comment]
you have to specify the full url in the callbackURL section of the strategy:
for example: when i'm running my code locally on localhost:3000 with code like this:
```
passport.use(new googleStrategy({

	clientID:keys.clientID,
	clientSecret:keys.clientSecret,
	callbackURL:'auth/google/callback'
},(accessToken,refreshToken, profile,done)=>{

	console.log(accessToken);
	console.log(refreshToken);
	console.log(profile);
}
));

app.get('/auth',passport.authenticate('google',{

	scope:['profile','email']
}));

app.get('/auth/google/callback', 
  passport.authenticate('google'));
```
The above code will surely throw an error like token:Bad request. so you have pass the complete URl
so the final code will be:

```
passport.use(new googleStrategy({

	clientID:keys.clientID,
	clientSecret:keys.clientSecret,
	callbackURL:'http://localhost:3000/auth/google/callback'
},(accessToken,refreshToken, profile,done)=>{

	console.log(accessToken);
	console.log(refreshToken);
	console.log(profile);
}
));

app.get('/auth',passport.authenticate('google',{

	scope:['profile','email']
}));

app.get('/auth/google/callback', 
  passport.authenticate('google'));

```

**Comment by shubham2896yadav** [comment]
i am wondering that why just this happen as i had used passport google for authentication.and i also make a call to drive api so that i am getting the drives data of users in my app easily and access token as well in my console but on the web page i am getting error as :: bad request or code is already redeemed

**Comment by seif1000** [comment]
when I console.log(profile) I can not get the user profile it shows me just [object object]? i am sorry for my bad english.

**Comment by rinzinsama** [comment]
Hello.. Is there an answer in this problem ? 

TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\dc\Documents\cc\node_modules\passport-oauth2\lib\strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\dc\Documents\cc\node_modules\passport-oauth2\lib\strategy.js:376:16)
    at C:\Users\dc\Documents\cc\node_modules\passport-oauth2\lib\strategy.js:166:45
    at C:\Users\dc\Documents\cc\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\dc\Documents\cointrade\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\dc\Documents\cc\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by bildo17** [comment]
I'm having the same problem having already tried out every solution mentioned above. Keys are fine, dev and prod env on heroku are setup ok...

I suspect the problem is with the strategy but I can't finger it out. When I console log I can see the user profile but for the oddest reason I keep getting thrown to a Tokken error.

Here's my code:

```
passport.use(
  new OAuth2Strategy(
 {
 clientID: keys.googleClientID,
 clientSecret: keys.googleClientSecret,
 callbackURL: keys.googleCallBackUrl,
 proxy: true
 },
(accessToken, refreshToken, profile, done) => {
console.log(accessToken);     
console.log(refreshToken);     
console.log(profile);     
new User({ googleId: profile.id }).save();     
}
));
```

```
app.get("/auth/google/callback", passport.authenticate("google")),
app.get("/logout", (req, res) => {
req.logout();
res.redirect("/");
});
```

**Comment by lmilliken** [comment]
After reviewing the other passport strategy examples (GitHub), I think what is missing is the done callback in the passport callback, like this:

```
passport.use(
  new GoogleStrategy(
    {
      clientID: config.google.clientID,
      clientSecret: config.google.clientSecret,
      callbackURL: '/auth/google/redirect'
    },
    function(accessToken, refreshToken, profile, done) {
      new User({
        username: profile.username,
        providerId: profile.id,
        provider: 'Google'
      })
        .save()
        .then((user) => {
          console.log({ user });
          done(null, user); //callback to let passport know that we are done processing
        });
    }
  )
);
```

**Comment by cdavidd** [comment]
![4-39](https://user-images.githubusercontent.com/43444343/59545737-689a2480-8ee8-11e9-8a19-9f301954686c.JPG)

https://github.com/cdavidd/emaily/blob/master/services/passport.js

i am having this issue, i dont know why, im trying to save in the database, and everithing is cool with that, but i dont know if is a google authenticator problem, here is mi code in my repo.

or I don't know if is this line in passport.js

new User({ googleId: profile.id }).save();

**Comment by bogdanmartinescu** [comment]
Hello all,

I had the same issue, and it got fixed once I removed the absolute path from the callbackURL in passport setup

```javascript 
    passport.use(new Strategy({
        clientID: GOOGLE_CLIENT_ID,
        clientSecret: GOOGLE_CLIENT_SECRET,
        callbackURL: `/api/${API_VERSION}/auth/google/callback`,
        passReqToCallback: true
    }
```
instead of 
```
 callbackURL: `http://localhost:4000/api/${API_VERSION}/auth/google/callback`
```
Hopefully this will help at least some of you

**Comment by dpk1391981** [comment]
passport.use(
        new GoogleStrategy({
            clientID: "********************"
            clientSecret: "********************",
            callbackURL: 'http://localhost:5000/auth/google/callback',
            proxy: true,
        }, (accessToken, refressToken, profile, done) => {
           //your code stuff.
        }),
    )

**Comment by sachuu96** [comment]
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/sachi/Desktop/oauth-playlist/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/sachi/Desktop/oauth-playlist/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /Users/sachi/Desktop/oauth-playlist/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /Users/sachi/Desktop/oauth-playlist/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/sachi/Desktop/oauth-playlist/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/sachi/Desktop/oauth-playlist/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

I get this error. I have already changed to callback URL as well

```
passport.use(
    new GoogleStrategy({
        // options for google strategy
        callbackURL:'http://127.0.0.1:3001/auth/google/redirect',
        clientID:keys.google.clientID,
        clientSecret:keys.google.clientSecret
    }, (accessToken,refreshToken,profile,done) => {
        // passport callback function
        console.log("passport callback function fired");
        console.log(profile);
    })
);
```

**Comment by sebbersk** [comment]
I tried everything above still get the bad request error. So I tried something and removed the passport.authenticate from the callback:

```
app.get('/auth/google/callback', 
  ~~passport.authenticate('google', { failureRedirect: '/login' })~~,
  function(req, res) {
    // Successful authentication, redirect home.
    res.redirect('/');
  });
```
And the error disappeared, Not sure if it is the right thing to do though...

**Comment by Isabanur** [comment]
I'm experiencing the same problem but it seems weird that some have removed the absolute path to the callback url and some have added it to solve the problem.
i gt the error with a relative path and it works with the absolute one.

**Comment by vishwa3** [comment]
I am also getting `TokenError: Bad Request`

**Comment by dpk1391981** [comment]
it will work for you.
new GoogleStrategy({
            clientID: keys.googleClientId,
            clientSecret: keys.googeClientSecret,
            callbackURL: 'http://localhost:9000/auth/google/callback',
            proxy: true,
        })

**Comment by nameeshgabru** [comment]
For me the problem was with final req handler, res.redirect('#/after-auth'); was casing this error.
router.get('/google/callback',
    passport.authenticate('google', { failureRedirect: '/login' }),
    function (req, res) {
        res.redirect('#/after-auth');
    }
);
changing to res.redirect('/#/after-auth'); helped.
router.get('/google/callback',
    passport.authenticate('google', { failureRedirect: '/login' }),
    function (req, res) {
        res.redirect('/#/after-auth');
    }
);

**Comment by himalay12345** [comment]
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:175:45
    at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)


I am getting this same error, can someone please explain what to do.
All my routes are correctly setup and the callback URI is also correct.
I am struggling for a week , please help me out.

**Comment by himalay12345** [comment]
> TokenError: Bad Request
> at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:358:12)
> at Strategy.OAuth2Strategy._createOAuthError (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:405:16)
> at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:175:45
> at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:191:18
> at passBackControl (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:132:9)
> at IncomingMessage. (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:157:7)
> at IncomingMessage.emit (events.js:322:22)
> at endReadableNT (_stream_readable.js:1187:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> I am getting this same error, can someone please explain what to do.
> All my routes are correctly setup and the callback URI is also correct.
> I am struggling for a week , please help me out.

Resolved: error was in sending the callback user data
if anyone get the same error feel free to ask

**Comment by botv** [comment]
> After a bit of digging, it looks like failureRedirect is ONLY used for strategy 'failures' and not 'errors', which is what gets thrown if a Token has already been used/redeemed.
> 
> This is a bit confusing, I agree.
> 
> It's almost as if passport needs an additional option for 'errorRedirect'
> 
> You can handle this outside of passport by implementing your own error handling. For example:
> 
> ```js
> app.get('/auth/google/callback',
>   passport.authenticate('google'), // complete the authenticate using the google strategy
>   (err, req, res, next) => { // custom error handler to catch any errors, such as TokenError
>     if (err.name === 'TokenError') {
>      res.redirect('/auth/google'); // redirect them back to the login page
>     } else {
>      // Handle other errors here
>     }
>   },
>   (req, res) => { // On success, redirect back to '/'
>     res.redirect('/');
>   }
> );
> ```

Is there any reason there isn't an `errorRedirect` option for cases like this? Seems much cleaner than writing a custom handler.

**Comment by spsp008** [comment]
try adding these two lines in passport configuration
```
app.use(passport.initialize());
app.use(passport.session());
```
it worked for me

**Comment by Manthan-Asher** [comment]
> > TokenError: Bad Request
> > at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:358:12)
> > at Strategy.OAuth2Strategy._createOAuthError (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:405:16)
> > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:175:45
> > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:191:18
> > at passBackControl (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:132:9)
> > at IncomingMessage. (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:157:7)
> > at IncomingMessage.emit (events.js:322:22)
> > at endReadableNT (_stream_readable.js:1187:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)
> > I am getting this same error, can someone please explain what to do.
> > All my routes are correctly setup and the callback URI is also correct.
> > I am struggling for a week , please help me out.
> 
> Resolved: error was in sending the callback user data
> if anyone get the same error feel free to ask

Hey could you please tell how did you resolve this issue, I am also facing the same

**Comment by himalay12345** [comment]
> > > TokenError: Bad Request
> > > at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:358:12)
> > > at Strategy.OAuth2Strategy._createOAuthError (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:405:16)
> > > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:175:45
> > > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:191:18
> > > at passBackControl (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:132:9)
> > > at IncomingMessage. (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:157:7)
> > > at IncomingMessage.emit (events.js:322:22)
> > > at endReadableNT (_stream_readable.js:1187:12)
> > > at processTicksAndRejections (internal/process/task_queues.js:84:21)
> > > I am getting this same error, can someone please explain what to do.
> > > All my routes are correctly setup and the callback URI is also correct.
> > > I am struggling for a week , please help me out.
> > 
> > 
> > Resolved: error was in sending the callback user data
> > if anyone get the same error feel free to ask
> 
> Hey could you please tell how did you resolve this issue, I am also facing the same

send the whole code I will find it out.

**Comment by ibraheemmawwal** [comment]
> Hopefully this will help at least some of you

thanks was really helpful

**Comment by noorashref** [comment]
Please help how to fix this
TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (D:\Programming\pp\oauth-playlist-lesson-9\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\Programming\pp\oauth-playlist-lesson-9\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at D:\Programming\pp\oauth-playlist-lesson-9\node_modules\passport-oauth2\lib\strategy.js:175:45
    at D:\Programming\pp\oauth-playlist-lesson-9\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\Programming\pp\oauth-playlist-lesson-9\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\Programming\pp\oauth-playlist-lesson-9\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by allyjohn07** [comment]
> you have to specify the full url in the callbackURL section of the strategy:
> for example: when i'm running my code locally on localhost:3000 with code like this:
> 
> ```
> passport.use(new googleStrategy({
> 
> 	clientID:keys.clientID,
> 	clientSecret:keys.clientSecret,
> 	callbackURL:'auth/google/callback'
> },(accessToken,refreshToken, profile,done)=>{
> 
> 	console.log(accessToken);
> 	console.log(refreshToken);
> 	console.log(profile);
> }
> ));
> 
> app.get('/auth',passport.authenticate('google',{
> 
> 	scope:['profile','email']
> }));
> 
> app.get('/auth/google/callback', 
>   passport.authenticate('google'));
> ```
> 
> The above code will surely throw an error like token:Bad request. so you have pass the complete URl
> so the final code will be:
> 
> ```
> passport.use(new googleStrategy({
> 
> 	clientID:keys.clientID,
> 	clientSecret:keys.clientSecret,
> 	callbackURL:'http://localhost:3000/auth/google/callback'
> },(accessToken,refreshToken, profile,done)=>{
> 
> 	console.log(accessToken);
> 	console.log(refreshToken);
> 	console.log(profile);
> }
> ));
> 
> app.get('/auth',passport.authenticate('google',{
> 
> 	scope:['profile','email']
> }));
> 
> app.get('/auth/google/callback', 
>   passport.authenticate('google'));
> ```

this work fine. callbackURL:'http://localhost:3000/auth/google/callback

**Comment by Randomx24** [comment]
`TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by Raj305173** [comment]
> > TokenError: Bad Request
> > at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:358:12)
> > at Strategy.OAuth2Strategy._createOAuthError (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:405:16)
> > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\passport-oauth2\lib\strategy.js:175:45
> > at C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:191:18
> > at passBackControl (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:132:9)
> > at IncomingMessage. (C:\Users\himal\OneDrive\Desktop\Git\codeial\node_modules\oauth\lib\oauth2.js:157:7)
> > at IncomingMessage.emit (events.js:322:22)
> > at endReadableNT (_stream_readable.js:1187:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)
> > 
> > I am getting this same error, can someone please explain what to do.
> > All my routes are correctly setup and the callback URI is also correct.
> > I am struggling for a week , please help me out.
> 
> Resolved: error was in sending the callback user data
> if anyone get the same error feel free to ask

I am getting the same error can you tell me how can i solve?

**Comment by SerhiiZimovets** [comment]
i have this error (TokenError: Bad Request) on prod, but not always just sometimes we catch it, and i wondering what the reason, my investigation result is that inside passport logic we make request to google to try get token and get broken response, finally i could reproduce the error ,  during google log in login front send request to back like this (http://localhost:3000/auth/google/redirect?code=4%2F0Ad.... bla...bla...bla) the key is the code parameter, so if we try to make the request second time with the same code we get the error, i suppose because we already use code to authorize user, but main question WHY AND HOW it happens on front-end, why we make this request second time it is mystery for me, and additionally i reproduce the error accidentally, i found url in chrome history it was yesterday but today the url is gone) cant find it, some thoughts??? 
![image](https://github.com/jaredhanson/passport-google-oauth2/assets/132881036/4629bb2f-7ae7-478e-b452-1fa083ce56eb)

**Comment by aa-poorv** [comment]
Hey, anyone found any solution for this problem.

> i have this error (TokenError: Bad Request) on prod, but not always just sometimes we catch it, and i wondering what the reason, my investigation result is that inside passport logic we make request to google to try get token and get broken response, finally i could reproduce the error , during google log in login front send request to back like this (http://localhost:3000/auth/google/redirect?code=4%2F0Ad.... bla...bla...bla) the key is the code parameter, so if we try to make the request second time with the same code we get the error, i suppose because we already use code to authorize user, but main question WHY AND HOW it happens on front-end, why we make this request second time it is mystery for me, and additionally i reproduce the error accidentally, i found url in chrome history it was yesterday but today the url is gone) cant find it, some thoughts??? ![image](https://private-user-images.githubusercontent.com/132881036/258064630-4629bb2f-7ae7-478e-b452-1fa083ce56eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTIzMjMsIm5iZiI6MTcwOTcxMjAyMywicGF0aCI6Ii8xMzI4ODEwMzYvMjU4MDY0NjMwLTQ2MjliYjJmLTdhZTctNDc4ZS1iNDUyLTFmYTA4M2NlNTZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwODAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDRhMWRhMmQ1MGRkNjE1MTM4YjZlZDNmYzM4Y2U5YzVjNTM1YmMyMDdhOTFhNDNjNzQ3NzExZTkyNzYyNDRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irzLeRpEFXfogdXm1-tN6FRouvSf2Irf_FOHKAGjYYU)

Hey I am also facing same issue. Have you found the solution?
