### ISSUE TITLE
InternalOAuthError

### ISSUE THREAD

**Issue by Kamaraju333** [jaredhanson/passport-google-oauth2#16]
WHEN I TRYING TO LOGIN WITH GOOGLE OAUTH2 I SEE THIS ERROR 

InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/Users/kprat1/learning/passportexamples2/passport-examples/node_modules/passport-oauth2/lib/strategy.js:370:17)
    at /Users/kprat1/learning/passportexamples2/passport-examples/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/kprat1/learning/passportexamples2/passport-examples/node_modules/oauth/lib/oauth2.js:177:18
    at ClientRequest.<anonymous> (/Users/kprat1/learning/passportexamples2/passport-examples/node_modules/oauth/lib/oauth2.js:148:5)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at emitErrorNT (net.js:1250:8)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

**Comment by senseluo** [comment]
i got the same issue, how did you fix it?

**Comment by TingAlex** [comment]
I got the exactly same issue, so could you teach me how to fix it please? @Kamaraju333 @senseluo

**Comment by RedTailBullet** [comment]
Same issue happening again...

**Comment by senseluo** [comment]
Seems i did nothing but push it to production environment and everything works well again.
but in my local machine, this issue happening again and again.

**Comment by RedTailBullet** [comment]
@senseluo That happens on my side as well.

**Comment by gyszalai** [comment]
I had the same problem with getting the user profile. It seems that the userinfo URL has changed as Google shuts down google+

The default userinfo URL in passport-google-oauth2 is
https://www.googleapis.com/plus/v1/people/me

But the official userinfo URL seems to be:
 https://www.googleapis.com/oauth2/v3/userinfo

You can read more about Google OpenID Connect at https://developers.google.com/identity/protocols/OpenIDConnect#discovery

**Comment by gyszalai** [comment]
If you run your application in a Docker container, make sure that your Docker default bridge is
reconfigured as the default config is 172.x.x.x and in my case it conflicted with a google ip address 172.217.23.74

**Comment by spursy** [comment]
I have the same issue, Who could help me?

**Comment by TingAlex** [comment]
> I have the same issue, Who could help me?

Have you tried use a global proxy? Only in case you are unfortunately located in China like me...

**Comment by ThomasLai1991** [comment]
> > I have the same issue, Who could help me?
> 
> Have you tried use a global proxy? Only in case you are unfortunately located in China like me...

I have this issue as well, and I am in China, how to fix this then? Is it something to do with proxy or vpn? thank you

**Comment by matinzd** [comment]
I have the same issue when I run this inside docker container with Nginx reverse proxy configured.
