### ISSUE TITLE
Authentication fails with Error

### ISSUE THREAD

**Issue by ughitsaaron** [jaredhanson/passport-google-oauth2#21]
I have some pretty straightforward boilerplate authentication code that fails,

```
router.get('/auth/google',
  passport.authenticate('google', { scope: ['profile', 'email'] }));

router.get('/auth/google/return',
  passport.authenticate('google', { failureRedirect: '/' }),
  function (req, res) {
    res.redirect('/');
  });
```

Upon being returned to `/auth/google/return` I'm given a vague Error,

```
Error
    at /Users/apetcoff/i liek 2 progrmam/my-project/node_modules/passport-google-oauth20/lib/strategy.js:95:21
    at passBackControl (/Users/apetcoff/i liek 2 progrmam/my-project/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/apetcoff/i liek 2 progrmam/my-project/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Facebook and Twitter authentication both work fine.

**Comment by devinsba** [comment]
@ughitsaaron @gittheking

You need to enable the Google+ Social API for your Google API project

**Comment by yoanisgil** [comment]
I get a similar stack trace:

```
    at /Users/ygil/Documents/Projects/express-4.x-facebook-example/node_modules/passport-google-oauth20/lib/strategy.js:95:21
    at passBackControl (/Users/ygil/Documents/Projects/express-4.x-facebook-example/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/ygil/Documents/Projects/express-4.x-facebook-example/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
I also enable Google+ API. I also enabled Google+ Domains API because we're using G Suite. Any ideas what I might be missing?

**Comment by AnupJai** [comment]
I am facing the same issue even after enabling the Google+ Social API. Have you got any solution?

**Comment by OllieJennings** [comment]
@AnupJai not sure if you are still having this issue but you need to enable both `Google+ API` && `Google People API`

**Comment by pranavQ** [comment]
Google will be closing the G+ from 7th March 2019.
