### ISSUE TITLE
Error on callback route with passport `Error at Strategy.OAuth2Strategy.parseErrorResponse`

### ISSUE THREAD

**Issue by KonradLinkowski** [jaredhanson/passport-google-oauth2#47]
`Error
at Strategy.OAuth2Strategy.parseErrorResponse (E:\Programowanie\NodeJS\Hydronide\node_modules\passport-oauth2\lib\strategy.js:329:12)
at Strategy.OAuth2Strategy._createOAuthError (E:\Programowanie\NodeJS\Hydronide\node_modules\passport-oauth2\lib\strategy.js:376:16)
at E:\Programowanie\NodeJS\Hydronide\node_modules\passport-oauth2\lib\strategy.js:166:45
at E:\Programowanie\NodeJS\Hydronide\node_modules\oauth\lib\oauth2.js:191:18
at passBackControl (E:\Programowanie\NodeJS\Hydronide\node_modules\oauth\lib\oauth2.js:132:9)
at IncomingMessage.<anonymous> (E:\Programowanie\NodeJS\Hydronide\node_modules\oauth\lib\oauth2.js:157:7)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1059:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)`

[Stackoverflow question](https://stackoverflow.com/questions/51226112/error-at-strategy-oauth2strategy-parseerrorresponse-nodejs-passport-google-oau)

**Comment by KonradLinkowski** [comment]
I found out that the problem is caused by callback url mismatch. But it still shouldn't work like that. The error name and description should be printed.

**Comment by anubhavcse08** [comment]
Solution:
I was using the same API credentials in both development and staging so Google wouldn't let me create a sign in on the same app (in it's eyes) from two locations.

@KonradLinkowski  If you already have a project in the API console you're using, go to https://console.developers.google.com, click "APIs & auth", "APIs", "Google+ API", "Enable API". Otherwise create a new project and do that.

**Comment by AHAMES** [comment]
but how do you fix that mismatch ?
