### ISSUE TITLE
ReferenceError: User is not defined      

### ISSUE THREAD

**Issue by SAMRITIS** [jaredhanson/passport-google-oauth2#68]
ReferenceError: User is not defined
    at Strategy._verify (C:\Users\root\Desktop\app\server.js:25:5)
    at C:\Users\root\Desktop\app\node_modules\passport-oauth2\lib\strategy.js:202:24
    at C:\Users\root\Desktop\app\node_modules\passport-google-oauth20\lib\strategy.js:122:5
    at passBackControl (C:\Users\root\Desktop\app\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\root\Desktop\app\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by toritsejuFO** [comment]
Duplicate of #67
