### ISSUE TITLE
cannot install npm install passport-google-oauth20

### ISSUE THREAD

**Issue by sihamlamssaoui** [jaredhanson/passport-google-oauth2#75]
TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/siham/.npm-global/lib/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/siham/.npm-global/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
    at Module._compile (module.js:653:30)
/home/siham/.npm-global/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (/home/siham/.npm-global/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163:13)
    at process.errorHandler (/home/siham/.npm-global/lib/node_modules/npm/lib/utils/error-handler.js:171:32)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)

**Comment by aryan4559** [comment]
Try update npm,` npm update`
then go for npm `npm install passport-google-oauth20`
